=== peterjavaee/jsf-flex/branches/release-1.1b/jsf-flex-shared/core/src/main/resources/META-INF/componentValueMapper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
			targetNamespace="http://jsf-flex.googlecode.com" 
			xmlns:compValMapper="http://jsf-flex.googlecode.com"
			elementFormDefault="qualified">
	<xs:annotation>
		<xs:documentation xml:lang="en-US">
			This schema is for componentValueMapper.xml, which is used to fetch Flex component's reflected persistent attribute for server side mapping.
		</xs:documentation>
		<xs:appinfo>
			<associatedXml>componentValueMapper.xml</associatedXml>
			<version>1.1b</version>
		</xs:appinfo>
	</xs:annotation>
	
	<xs:element name="classLists">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="classInfo" maxOccurs="unbounded">
					<xs:complexType>
						<xs:all>
							<xs:element name="className" type="xs:string"></xs:element>
							<xs:element name="nodeList">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="node" maxOccurs="unbounded">
											<xs:complexType>
												<xs:all>
													<xs:element name="htmlType" type="xs:string"></xs:element>
													<xs:element name="attributeList" type="compValMapper:attributeList"></xs:element>
												</xs:all>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:all>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="attributeList">
		<xs:sequence>
			<xs:element name="attribute" minOccurs="3" maxOccurs="3">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="type"></xs:enumeration>
									<xs:enumeration value="value"></xs:enumeration>
									<xs:enumeration value="name"></xs:enumeration>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="value">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="nested" minOccurs="0" maxOccurs="unbounded" type="xs:string"></xs:element>
								</xs:sequence>
								<xs:attribute name="dynamic" type="compValMapper:booleanValue"></xs:attribute>
								<xs:attribute name="nested" type="compValMapper:booleanValue"></xs:attribute>
								<xs:attribute name="append" type="xs:string"></xs:attribute>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:simpleType name="booleanValue">
		<xs:restriction base="xs:string">
			<xs:enumeration value="true"></xs:enumeration>
			<xs:enumeration value="false"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== peterjavaee/jsf-flex/wiki/componentValueMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<classLists xmlns="http://jsf-flex.googlecode.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://jsf-flex.googlecode.com componentValueMapper.xsd ">
<classInfo>
<className>spark.components::CheckBox</className>
<nodeList>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">selected</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_selected">id</value>
</attribute>
</attributeList>
</node>
</nodeList>
</classInfo>
<classInfo>
<className>spark.components::HSlider</className>
<nodeList>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">value</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_value">id</value>
</attribute>
</attributeList>
</node>
</nodeList>
</classInfo>
<classInfo>
<className>mx.containers::TabNavigator</className>
<nodeList>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">selectedIndex</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_selectedIndex">id</value>
</attribute>
</attributeList>
</node>
</nodeList>
</classInfo>
<classInfo>
<className>spark.components::TextInput</className>
<nodeList>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">text</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_text">id</value>
</attribute>
</attributeList>
</node>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">htmlText</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_htmlText">id</value>
</attribute>
</attributeList>
</node>
</nodeList>
</classInfo>
<classInfo>
<className>mx.controls::TileList</className>
<nodeList>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">selectedIndex</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_selectedIndex">id</value>
</attribute>
</attributeList>
</node>
</nodeList>
</classInfo>
<classInfo>
<className>spark.components::Spinner</className>
<nodeList>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">value</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_value">id</value>
</attribute>
</attributeList>
</node>
</nodeList>
</classInfo>
<classInfo>
<className>spark.components::ToggleButton</className>
<nodeList>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">selected</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_selected">id</value>
</attribute>
</attributeList>
</node>
</nodeList>
</classInfo>
<classInfo>
<className>mx.controls::ProgressBar</className>
<nodeList>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">value</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_value">id</value>
</attribute>
</attributeList>
</node>
</nodeList>
</classInfo>
<classInfo>
<className>mx.containers::Accordion</className>
<nodeList>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">selectedIndex</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_selectedIndex">id</value>
</attribute>
</attributeList>
</node>
</nodeList>
</classInfo>
<classInfo>
<className>mx.controls::ColorPicker</className>
<nodeList>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">selectedColor</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_selectedColor">id</value>
</attribute>
</attributeList>
</node>
</nodeList>
</classInfo>
<classInfo>
<className>spark.components::TabBar</className>
<nodeList>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">selectedIndex</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_selectedIndex">id</value>
</attribute>
</attributeList>
</node>
</nodeList>
</classInfo>
<classInfo>
<className>spark.components::RadioButton</className>
<nodeList>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true" nested="true">
<nested>group</nested>
<nested>selectedValue</nested>
</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_selectedValue">groupName</value>
</attribute>
</attributeList>
</node>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">selected</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_selected">id</value>
</attribute>
</attributeList>
</node>
</nodeList>
</classInfo>
<classInfo>
<className>spark.components::ComboBox</className>
<nodeList>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">text</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_text">id</value>
</attribute>
</attributeList>
</node>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">selectedIndex</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_selectedIndex">id</value>
</attribute>
</attributeList>
</node>
</nodeList>
</classInfo>
<classInfo>
<className>spark.components::RichEditableText</className>
<nodeList>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">text</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_text">id</value>
</attribute>
</attributeList>
</node>
</nodeList>
</classInfo>
<classInfo>
<className>mx.controls::DateField</className>
<nodeList>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">text</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_text">id</value>
</attribute>
</attributeList>
</node>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">selectedDate</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_selectedDate">id</value>
</attribute>
</attributeList>
</node>
</nodeList>
</classInfo>
<classInfo>
<className>spark.components::VSlider</className>
<nodeList>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">value</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_value">id</value>
</attribute>
</attributeList>
</node>
</nodeList>
</classInfo>
<classInfo>
<className>mx.controls::Tree</className>
<nodeList>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">selectedIndex</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_selectedIndex">id</value>
</attribute>
</attributeList>
</node>
</nodeList>
</classInfo>
<classInfo>
<className>spark.components::List</className>
<nodeList>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">selectedIndex</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_selectedIndex">id</value>
</attribute>
</attributeList>
</node>
</nodeList>
</classInfo>
<classInfo>
<className>spark.components::DropDownList</className>
<nodeList>
<node>
<htmlType>input</htmlType>
<attributeList>
<attribute>
<name>type</name>
<value>hidden</value>
</attribute>
<attribute>
<name>value</name>
<value dynamic="true">selectedIndex</value>
</attribute>
<attribute>
<name>name</name>
<value dynamic="true" append="_selectedIndex">id</value>
</attribute>
</attributeList>
</node>
</nodeList>
</classInfo>
